// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: api/airtel/airtel.proto

package airtel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AirtelAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrantType    string `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ClientId     string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *AirtelAuthRequest) Reset() {
	*x = AirtelAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelAuthRequest) ProtoMessage() {}

func (x *AirtelAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelAuthRequest.ProtoReflect.Descriptor instead.
func (*AirtelAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{0}
}

func (x *AirtelAuthRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *AirtelAuthRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AirtelAuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AirtelAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn   int64  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType   string `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
}

func (x *AirtelAuthResponse) Reset() {
	*x = AirtelAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelAuthResponse) ProtoMessage() {}

func (x *AirtelAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelAuthResponse.ProtoReflect.Descriptor instead.
func (*AirtelAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{1}
}

func (x *AirtelAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AirtelAuthResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AirtelAuthResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type MMPAirtelCollectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber   string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Amount        string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference     string `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Transactionid string `protobuf:"bytes,4,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
}

func (x *MMPAirtelCollectionRequest) Reset() {
	*x = MMPAirtelCollectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MMPAirtelCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MMPAirtelCollectionRequest) ProtoMessage() {}

func (x *MMPAirtelCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MMPAirtelCollectionRequest.ProtoReflect.Descriptor instead.
func (*MMPAirtelCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{2}
}

func (x *MMPAirtelCollectionRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MMPAirtelCollectionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MMPAirtelCollectionRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *MMPAirtelCollectionRequest) GetTransactionid() string {
	if x != nil {
		return x.Transactionid
	}
	return ""
}

type AirtelCollectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference   string                               `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Transaction *AirtelCollectionRequest_Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Subscriber  *AirtelCollectionRequest_Subscriber  `protobuf:"bytes,3,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
}

func (x *AirtelCollectionRequest) Reset() {
	*x = AirtelCollectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionRequest) ProtoMessage() {}

func (x *AirtelCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionRequest.ProtoReflect.Descriptor instead.
func (*AirtelCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{3}
}

func (x *AirtelCollectionRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *AirtelCollectionRequest) GetTransaction() *AirtelCollectionRequest_Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *AirtelCollectionRequest) GetSubscriber() *AirtelCollectionRequest_Subscriber {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

type AirtelCollectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *AirtelCollectionResponse_Data   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status *AirtelCollectionResponse_Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AirtelCollectionResponse) Reset() {
	*x = AirtelCollectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionResponse) ProtoMessage() {}

func (x *AirtelCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionResponse.ProtoReflect.Descriptor instead.
func (*AirtelCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{4}
}

func (x *AirtelCollectionResponse) GetData() *AirtelCollectionResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AirtelCollectionResponse) GetStatus() *AirtelCollectionResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type AirtelCollectionStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactionid string `protobuf:"bytes,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
}

func (x *AirtelCollectionStatusRequest) Reset() {
	*x = AirtelCollectionStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionStatusRequest) ProtoMessage() {}

func (x *AirtelCollectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionStatusRequest.ProtoReflect.Descriptor instead.
func (*AirtelCollectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{5}
}

func (x *AirtelCollectionStatusRequest) GetTransactionid() string {
	if x != nil {
		return x.Transactionid
	}
	return ""
}

type AirtelCollectionStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *AirtelCollectionStatusResponse_Data   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status *AirtelCollectionStatusResponse_Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AirtelCollectionStatusResponse) Reset() {
	*x = AirtelCollectionStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionStatusResponse) ProtoMessage() {}

func (x *AirtelCollectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionStatusResponse.ProtoReflect.Descriptor instead.
func (*AirtelCollectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{6}
}

func (x *AirtelCollectionStatusResponse) GetData() *AirtelCollectionStatusResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AirtelCollectionStatusResponse) GetStatus() *AirtelCollectionStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type AirtelCollectionRequest_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount   string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Country  string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AirtelCollectionRequest_Transaction) Reset() {
	*x = AirtelCollectionRequest_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionRequest_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionRequest_Transaction) ProtoMessage() {}

func (x *AirtelCollectionRequest_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionRequest_Transaction.ProtoReflect.Descriptor instead.
func (*AirtelCollectionRequest_Transaction) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AirtelCollectionRequest_Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AirtelCollectionRequest_Transaction) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AirtelCollectionRequest_Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AirtelCollectionRequest_Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AirtelCollectionRequest_Subscriber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country  string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Currency string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Msisdn   string `protobuf:"bytes,3,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
}

func (x *AirtelCollectionRequest_Subscriber) Reset() {
	*x = AirtelCollectionRequest_Subscriber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionRequest_Subscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionRequest_Subscriber) ProtoMessage() {}

func (x *AirtelCollectionRequest_Subscriber) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionRequest_Subscriber.ProtoReflect.Descriptor instead.
func (*AirtelCollectionRequest_Subscriber) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AirtelCollectionRequest_Subscriber) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AirtelCollectionRequest_Subscriber) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AirtelCollectionRequest_Subscriber) GetMsisdn() string {
	if x != nil {
		return x.Msisdn
	}
	return ""
}

type AirtelCollectionResponse_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AirtelCollectionResponse_Transaction) Reset() {
	*x = AirtelCollectionResponse_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionResponse_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionResponse_Transaction) ProtoMessage() {}

func (x *AirtelCollectionResponse_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionResponse_Transaction.ProtoReflect.Descriptor instead.
func (*AirtelCollectionResponse_Transaction) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AirtelCollectionResponse_Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AirtelCollectionResponse_Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AirtelCollectionResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *AirtelCollectionResponse_Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *AirtelCollectionResponse_Data) Reset() {
	*x = AirtelCollectionResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionResponse_Data) ProtoMessage() {}

func (x *AirtelCollectionResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionResponse_Data.ProtoReflect.Descriptor instead.
func (*AirtelCollectionResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{4, 1}
}

func (x *AirtelCollectionResponse_Data) GetTransaction() *AirtelCollectionResponse_Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type AirtelCollectionResponse_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode string `protobuf:"bytes,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Code         string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Success      string `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"`
	ResultCode   string `protobuf:"bytes,4,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Message      string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AirtelCollectionResponse_Status) Reset() {
	*x = AirtelCollectionResponse_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionResponse_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionResponse_Status) ProtoMessage() {}

func (x *AirtelCollectionResponse_Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionResponse_Status.ProtoReflect.Descriptor instead.
func (*AirtelCollectionResponse_Status) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{4, 2}
}

func (x *AirtelCollectionResponse_Status) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *AirtelCollectionResponse_Status) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AirtelCollectionResponse_Status) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *AirtelCollectionResponse_Status) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *AirtelCollectionResponse_Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AirtelCollectionStatusResponse_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AirtelMoneyId string `protobuf:"bytes,1,opt,name=airtel_money_id,json=airtelMoneyId,proto3" json:"airtel_money_id,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AirtelCollectionStatusResponse_Transaction) Reset() {
	*x = AirtelCollectionStatusResponse_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionStatusResponse_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionStatusResponse_Transaction) ProtoMessage() {}

func (x *AirtelCollectionStatusResponse_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionStatusResponse_Transaction.ProtoReflect.Descriptor instead.
func (*AirtelCollectionStatusResponse_Transaction) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AirtelCollectionStatusResponse_Transaction) GetAirtelMoneyId() string {
	if x != nil {
		return x.AirtelMoneyId
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Transaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AirtelCollectionStatusResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *AirtelCollectionStatusResponse_Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *AirtelCollectionStatusResponse_Data) Reset() {
	*x = AirtelCollectionStatusResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionStatusResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionStatusResponse_Data) ProtoMessage() {}

func (x *AirtelCollectionStatusResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionStatusResponse_Data.ProtoReflect.Descriptor instead.
func (*AirtelCollectionStatusResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{6, 1}
}

func (x *AirtelCollectionStatusResponse_Data) GetTransaction() *AirtelCollectionStatusResponse_Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type AirtelCollectionStatusResponse_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode string `protobuf:"bytes,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Code         string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Success      string `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"`
	ResultCode   string `protobuf:"bytes,4,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Message      string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AirtelCollectionStatusResponse_Status) Reset() {
	*x = AirtelCollectionStatusResponse_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_airtel_airtel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirtelCollectionStatusResponse_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtelCollectionStatusResponse_Status) ProtoMessage() {}

func (x *AirtelCollectionStatusResponse_Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_airtel_airtel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtelCollectionStatusResponse_Status.ProtoReflect.Descriptor instead.
func (*AirtelCollectionStatusResponse_Status) Descriptor() ([]byte, []int) {
	return file_api_airtel_airtel_proto_rawDescGZIP(), []int{6, 2}
}

func (x *AirtelCollectionStatusResponse_Status) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Status) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Status) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Status) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *AirtelCollectionStatusResponse_Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_airtel_airtel_proto protoreflect.FileDescriptor

var file_api_airtel_airtel_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2f, 0x61, 0x69, 0x72,
	0x74, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x69, 0x72, 0x74, 0x65,
	0x6c, 0x22, 0x74, 0x0a, 0x11, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x61, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x12, 0x41, 0x69, 0x72, 0x74, 0x65,
	0x6c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9a,
	0x01, 0x0a, 0x1a, 0x4d, 0x4d, 0x50, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x22, 0x9b, 0x03, 0x0a, 0x17,
	0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x69, 0x72,
	0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65,
	0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72,
	0x1a, 0x6b, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x5a, 0x0a,
	0x0a, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x22, 0xbe, 0x03, 0x0a, 0x18, 0x41, 0x69,
	0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69,
	0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74, 0x65,
	0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x1a, 0x35, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x56, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x4e, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e,
	0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x96, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x45, 0x0a, 0x1d, 0x41, 0x69,
	0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x69,
	0x64, 0x22, 0x98, 0x04, 0x0a, 0x1e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74,
	0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x45, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41,
	0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x77, 0x0a, 0x0b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x61,
	0x69, 0x72, 0x74, 0x65, 0x6c, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x5c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x54, 0x0a,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74,
	0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x96, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x97, 0x02, 0x0a,
	0x0d, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x0a, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x12, 0x19, 0x2e, 0x61,
	0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c,
	0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x10, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c,
	0x2e, 0x4d, 0x4d, 0x50, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x69,
	0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a,
	0x16, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c,
	0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x2e, 0x41, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x79, 0x67, 0x6f, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x69, 0x72, 0x74, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_airtel_airtel_proto_rawDescOnce sync.Once
	file_api_airtel_airtel_proto_rawDescData = file_api_airtel_airtel_proto_rawDesc
)

func file_api_airtel_airtel_proto_rawDescGZIP() []byte {
	file_api_airtel_airtel_proto_rawDescOnce.Do(func() {
		file_api_airtel_airtel_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_airtel_airtel_proto_rawDescData)
	})
	return file_api_airtel_airtel_proto_rawDescData
}

var file_api_airtel_airtel_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_airtel_airtel_proto_goTypes = []interface{}{
	(*AirtelAuthRequest)(nil),                          // 0: airtel.AirtelAuthRequest
	(*AirtelAuthResponse)(nil),                         // 1: airtel.AirtelAuthResponse
	(*MMPAirtelCollectionRequest)(nil),                 // 2: airtel.MMPAirtelCollectionRequest
	(*AirtelCollectionRequest)(nil),                    // 3: airtel.AirtelCollectionRequest
	(*AirtelCollectionResponse)(nil),                   // 4: airtel.AirtelCollectionResponse
	(*AirtelCollectionStatusRequest)(nil),              // 5: airtel.AirtelCollectionStatusRequest
	(*AirtelCollectionStatusResponse)(nil),             // 6: airtel.AirtelCollectionStatusResponse
	(*AirtelCollectionRequest_Transaction)(nil),        // 7: airtel.AirtelCollectionRequest.Transaction
	(*AirtelCollectionRequest_Subscriber)(nil),         // 8: airtel.AirtelCollectionRequest.Subscriber
	(*AirtelCollectionResponse_Transaction)(nil),       // 9: airtel.AirtelCollectionResponse.Transaction
	(*AirtelCollectionResponse_Data)(nil),              // 10: airtel.AirtelCollectionResponse.Data
	(*AirtelCollectionResponse_Status)(nil),            // 11: airtel.AirtelCollectionResponse.Status
	(*AirtelCollectionStatusResponse_Transaction)(nil), // 12: airtel.AirtelCollectionStatusResponse.Transaction
	(*AirtelCollectionStatusResponse_Data)(nil),        // 13: airtel.AirtelCollectionStatusResponse.Data
	(*AirtelCollectionStatusResponse_Status)(nil),      // 14: airtel.AirtelCollectionStatusResponse.Status
}
var file_api_airtel_airtel_proto_depIdxs = []int32{
	7,  // 0: airtel.AirtelCollectionRequest.transaction:type_name -> airtel.AirtelCollectionRequest.Transaction
	8,  // 1: airtel.AirtelCollectionRequest.subscriber:type_name -> airtel.AirtelCollectionRequest.Subscriber
	10, // 2: airtel.AirtelCollectionResponse.data:type_name -> airtel.AirtelCollectionResponse.Data
	11, // 3: airtel.AirtelCollectionResponse.status:type_name -> airtel.AirtelCollectionResponse.Status
	13, // 4: airtel.AirtelCollectionStatusResponse.data:type_name -> airtel.AirtelCollectionStatusResponse.Data
	14, // 5: airtel.AirtelCollectionStatusResponse.status:type_name -> airtel.AirtelCollectionStatusResponse.Status
	9,  // 6: airtel.AirtelCollectionResponse.Data.transaction:type_name -> airtel.AirtelCollectionResponse.Transaction
	12, // 7: airtel.AirtelCollectionStatusResponse.Data.transaction:type_name -> airtel.AirtelCollectionStatusResponse.Transaction
	0,  // 8: airtel.AirtelService.AirtelAuth:input_type -> airtel.AirtelAuthRequest
	2,  // 9: airtel.AirtelService.AirtelCollection:input_type -> airtel.MMPAirtelCollectionRequest
	5,  // 10: airtel.AirtelService.AirtelCollectionStatus:input_type -> airtel.AirtelCollectionStatusRequest
	1,  // 11: airtel.AirtelService.AirtelAuth:output_type -> airtel.AirtelAuthResponse
	4,  // 12: airtel.AirtelService.AirtelCollection:output_type -> airtel.AirtelCollectionResponse
	6,  // 13: airtel.AirtelService.AirtelCollectionStatus:output_type -> airtel.AirtelCollectionStatusResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_airtel_airtel_proto_init() }
func file_api_airtel_airtel_proto_init() {
	if File_api_airtel_airtel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_airtel_airtel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MMPAirtelCollectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionRequest_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionRequest_Subscriber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionResponse_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionResponse_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionStatusResponse_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionStatusResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_airtel_airtel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirtelCollectionStatusResponse_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_airtel_airtel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_airtel_airtel_proto_goTypes,
		DependencyIndexes: file_api_airtel_airtel_proto_depIdxs,
		MessageInfos:      file_api_airtel_airtel_proto_msgTypes,
	}.Build()
	File_api_airtel_airtel_proto = out.File
	file_api_airtel_airtel_proto_rawDesc = nil
	file_api_airtel_airtel_proto_goTypes = nil
	file_api_airtel_airtel_proto_depIdxs = nil
}
