// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: api/sms/sms.proto

package sms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient []int64 `protobuf:"varint,1,rep,packed,name=recipient,proto3" json:"recipient,omitempty"`
	Message   string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Username  string  `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password  string  `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Senderid  string  `protobuf:"bytes,5,opt,name=senderid,proto3" json:"senderid,omitempty"`
	Source    string  `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	MsgRef    string  `protobuf:"bytes,7,opt,name=msg_ref,json=msgRef,proto3" json:"msg_ref,omitempty"`
}

func (x *SMSRequest) Reset() {
	*x = SMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSRequest) ProtoMessage() {}

func (x *SMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSRequest.ProtoReflect.Descriptor instead.
func (*SMSRequest) Descriptor() ([]byte, []int) {
	return file_api_sms_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SMSRequest) GetRecipient() []int64 {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *SMSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SMSRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SMSRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SMSRequest) GetSenderid() string {
	if x != nil {
		return x.Senderid
	}
	return ""
}

func (x *SMSRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SMSRequest) GetMsgRef() string {
	if x != nil {
		return x.MsgRef
	}
	return ""
}

type SMSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*SMSResponse_Response `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *SMSResponse) Reset() {
	*x = SMSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSResponse) ProtoMessage() {}

func (x *SMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSResponse.ProtoReflect.Descriptor instead.
func (*SMSResponse) Descriptor() ([]byte, []int) {
	return file_api_sms_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SMSResponse) GetResponse() []*SMSResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type SMSResponse_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile        string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Messagestatus string `protobuf:"bytes,2,opt,name=messagestatus,proto3" json:"messagestatus,omitempty"`
	Messageid     string `protobuf:"bytes,3,opt,name=messageid,proto3" json:"messageid,omitempty"`
}

func (x *SMSResponse_Response) Reset() {
	*x = SMSResponse_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_sms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSResponse_Response) ProtoMessage() {}

func (x *SMSResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_sms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSResponse_Response.ProtoReflect.Descriptor instead.
func (*SMSResponse_Response) Descriptor() ([]byte, []int) {
	return file_api_sms_sms_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SMSResponse_Response) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SMSResponse_Response) GetMessagestatus() string {
	if x != nil {
		return x.Messagestatus
	}
	return ""
}

func (x *SMSResponse_Response) GetMessageid() string {
	if x != nil {
		return x.Messageid
	}
	return ""
}

var File_api_sms_sms_proto protoreflect.FileDescriptor

var file_api_sms_sms_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6d, 0x73, 0x2f, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x53, 0x4d, 0x53,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x73,
	0x67, 0x52, 0x65, 0x66, 0x22, 0xac, 0x01, 0x0a, 0x0b, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x4d, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x66, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x69, 0x64, 0x32, 0x3a, 0x0a, 0x0a, 0x53, 0x4d, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2c, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x4d, 0x53, 0x12, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61,
	0x79, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sms_sms_proto_rawDescOnce sync.Once
	file_api_sms_sms_proto_rawDescData = file_api_sms_sms_proto_rawDesc
)

func file_api_sms_sms_proto_rawDescGZIP() []byte {
	file_api_sms_sms_proto_rawDescOnce.Do(func() {
		file_api_sms_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sms_sms_proto_rawDescData)
	})
	return file_api_sms_sms_proto_rawDescData
}

var file_api_sms_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_sms_sms_proto_goTypes = []interface{}{
	(*SMSRequest)(nil),           // 0: api.SMSRequest
	(*SMSResponse)(nil),          // 1: api.SMSResponse
	(*SMSResponse_Response)(nil), // 2: api.SMSResponse.Response
}
var file_api_sms_sms_proto_depIdxs = []int32{
	2, // 0: api.SMSResponse.response:type_name -> api.SMSResponse.Response
	0, // 1: api.SMSService.SendSMS:input_type -> api.SMSRequest
	1, // 2: api.SMSService.SendSMS:output_type -> api.SMSResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_sms_sms_proto_init() }
func file_api_sms_sms_proto_init() {
	if File_api_sms_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sms_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_sms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSResponse_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sms_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sms_sms_proto_goTypes,
		DependencyIndexes: file_api_sms_sms_proto_depIdxs,
		MessageInfos:      file_api_sms_sms_proto_msgTypes,
	}.Build()
	File_api_sms_sms_proto = out.File
	file_api_sms_sms_proto_rawDesc = nil
	file_api_sms_sms_proto_goTypes = nil
	file_api_sms_sms_proto_depIdxs = nil
}
